In [1]:
import geometricconvolutions.geometric as geom
import geometricconvolutions.utils as utils
import jax.numpy as jnp
import jax
import numpy as np
from functools import partial
import jax.random as random
import timeit

%load_ext autoreload
%autoreload 2

In [2]:
key = jax.random.PRNGKey(0)

In [7]:
D = 2
N = 3
parity = 0
k = 0
operators = geom.make_all_operators(D)
invariants = geom.get_unique_invariant_filters(N, k, parity, D, operators, scale='one')
names = ["{} {}".format(geom.tensor_name(k, parity), i) for i in range(len(invariants))]
len(invariants)
geom.LeviCivitaSymbol.get(2).T == geom.LeviCivitaSymbol.get(2)*-1

DeviceArray([[ True,  True],
             [ True,  True]], dtype=bool)

In [9]:
levi_image = geom.GeometricImage(geom.LeviCivitaSymbol.get(D).reshape((1,1,D,D)), 1, 2)
print(levi_image.data)
for gg in operators:
    print('element:')
    print(levi_image.times_group_element(gg).data)


[[[[ 0  1]
   [-1  0]]]]
element:
[[[[ 0.  1.]
   [-1.  0.]]]]
element:
[[[[-0.  1.]
   [-1. -0.]]]]
element:
[[[[-0.  1.]
   [-1. -0.]]]]
element:
[[[[ 0.  1.]
   [-1.  0.]]]]
element:
[[[[-0.  1.]
   [-1. -0.]]]]
element:
[[[[ 0.  1.]
   [-1.  0.]]]]
element:
[[[[ 0.  1.]
   [-1.  0.]]]]
element:
[[[[-0.  1.]
   [-1. -0.]]]]


In [ ]:
utils.plot_filters(invariants[:10], names, len(invariants[:10]))

In [4]:
# Make an N side length, parity=0 geometric vector image on a D-torus
key = random.PRNGKey(0)
img_k = 5

img = geom.GeometricImage(random.normal(key, shape=(N,)*D + (D,)*img_k), 0, D)
for idxs in geom.get_contraction_indices(img_k, 1):
    print('foo')
    img.multicontract(idxs)

foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling
foo
compiling


In [ ]:
print(len(vector_images))
params = jnp.arange(10)
image_sum = geom.linear_combination(vector_images, params)
print(image_sum)

In [ ]:
%timeit geom.linear_combination(vector_images, params).block_until_ready()

In [ ]:
jit_linear_combo = jax.jit(geom.linear_combination)
jit_linear_combo(vector_images, params)

In [ ]:
%timeit jit_linear_combo(vector_images, params).block_until_ready()

In [ ]:
def f(carry, x):
    return carry, x ** 2


jax.lax.scan(f, 1, [1,2,3])

